version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - HOSTNAME=postgres
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: always
  tomcat-eggobase:
    container_name: tomcat-eggobase
    image: tomcat-eggobase
    build: .
    depends_on: 
      - postgres
    ports:
      - 80:8080
    environment:
      - HOSTNAME=eggobase
      - DBNAME=eggobase
      - DBHOST=postgres
      - DBPORT=5432
      - DBUSER=postgres
      - DBPW=docker
    restart: always