version: '3'

services:
  postgres:
    container_name: postgres
    privileged: true
    image: postgres
    environment:
      - HOSTNAME=$HOSTNAME
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: always
  eggobase-tomcat:
    container_name: eggobase-tomcat
    privileged: true
    network_mode: host
    image: "lushdigital/lushroom-display:latest"
    ports:
      - 80:8080
    environment:
      - HOSTNAME=$HOSTNAME
    restart: always