apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose-factory
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: tomcat-eggobase
  name: tomcat-eggobase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tomcat-eggobase
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kompose-factory
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: tomcat-eggobase
    spec:
      containers:
      - env:
        - name: DBHOST
          value: postgres
        - name: DBNAME
          value: eggobase
        - name: DBPORT
          value: "5432"
        - name: DBPW
          value: docker
        - name: DBUSER
          value: postgres
        - name: HOSTNAME
          value: eggobase
        image: inbrewj/tomcat-eggobase
        imagePullPolicy: ""
        name: tomcat-eggobase
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
